const mongoose= require("mongoose")

const will = mongoose.Schema({
  
    requesterTitle: { type: String, required: true },
    requesterFname: {type:String, required: true},
    requesterMname: {type:String},
    requesterLname: {type:String, required: true},
    requesterAdd: {type:String, required: true},
    requesterEmail: {type:String, required: true},
    requesterPhNo: {type:String, required: true},
    requesterAddLine1: {type:String, required: true},
    requesterAddLine2: {type:String},
    requesterTown: {type:String, required: true},
    requesterCountry: {type:String, required: true},
    requesterPostCode: {type:String, required: true},
    promotionCode: {type:String, required: true},
    requesterSelfie: {type:String, required: true},
    willStatus:{type:String, required: true},
    willOwnerTitle: {type:String, required: true},
    willOwnerFname: {type:String, required: true},
    willOwnerMname: {type:String},
    willOwnerSurname: {type:String, required: true},
    willOwnerEmail:{type:String, required: true},
    willOwnerDob: {type:String, required: true},
    willOwnerGender: {type:String, required: true},
    willOwnerAddLine1: {type:String, required: true},
    willOwnerAddLine2: {type:String},
    willOwnerCity: {type:String, required: true},
    willOwnerCountry: {type:String, required: true},
    willOwnerUK: {type:String, required: true},
    willOwnerPostcode: {type:String, required: true},
    willOwnerPhNo:{type:String,required: true},
    executorName: {type:String},
    executorEmailAdd: {type:String},
    executorPhoneNo: {type:String},
    executorAddLine1: {type:String},
    executorAddLine2: {type:String},
    executorCity: {type:String},
    executorCountry: {type:String},
    dateOfWill: {type:String, required: true},
    storedWillAdd: {type:String, required: true},
    additionalIns: {type:String, required: true},
    willReminderFr: {type:String},
    lastRemDate: {type:String},
    nextRemDate: {type:String},
    createdWillPDF: {type:String},
    discountCode: {type:String},
    discountAmount: {type:String},
    dateCreated:{type:String}
  });
  
  module.exports = mongoose.model("will", will);